export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const ADD_TRANSACTION_COMPLETE = 'ADD_TRANSACTION_COMPLETE';

export const REMOVE_TRANSACTION = 'REMOVE_TRANSACTION';
export const REMOVE_TRANSACTION_COMPLETE = 'REMOVE_TRANSACTION_COMPLETE';


export const LOAD_BUDGET = 'LOAD_BUDGET';
export const LOAD_BUDGET_COMPLETE = 'LOAD_BUDGET_COMPLETE';

export const LOAD_BUDGET_DATA = 'LOAD_BUDGET_DATA';
export const LOAD_BUDGET_DATA_COMPLETE = 'LOAD_BUDGET_DATA_COMPLETE';
export const LOAD_BUDGET_DATA_FROM_CACHE = 'LOAD_BUDGET_DATA_FROM_CACHE';


export const ADD_BUDGET = 'ADD_BUDGET';
export const ADD_BUDGET_COMPLETE = 'ADD_BUDGET_COMPLETE';


export const UPDATE_BUDGET = 'UPDATE_BUDGET';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_COMPLETE = 'ADD_CATEGORY_COMPLETE';

export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';


export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
